FROM ubuntu:latest

# Update python, Install virtualenv, nginx, supervisor
RUN apt-get update --fix-missing  \ 
	&& apt-get install -y tmux software-properties-common gcc g++ binutils git \
	&& apt-get install -y python python-dev python-tk python-setuptools \
	&& apt-get install -y build-essential libblas-dev liblapack-dev \
        && apt-get install -y python-pip python-virtualenv \

# CUDA@ Toolkit 9.0
RUN wget https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda-repo-ubuntu1604-9-1-local_9.1.85-1_amd64
