FROM ubuntu:latest

# Update python, Install virtualenv, nginx, supervisor
RUN apt-get update --fix-missing  \ 
	&& apt-get install -y tmux wget software-properties-common gcc g++ binutils git \
	&& apt-get install -y python python-dev python-tk python-setuptools \
	&& apt-get install -y build-essential libblas-dev liblapack-dev \
        && apt-get install -y python-pip python-virtualenv \

